# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
      - Release*

stages:
  - stage: CI_Frontend
    displayName: 'CI for Frontend'
    jobs:
      - job: __CI__
        displayName: 'CI JOB for Frontend'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          - script: npm install
            displayName: install node dependencies
          - script: npm run build
            displayName: RUN BUILD
          - script: echo variables['Build.SourceBranch']

  - stage: CD_Frontend
    displayName: 'CD for Frontend'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/Release')
    jobs:
      - job: _CD_
        displayName: 'CD JOB for Frontend'
        steps:
          - script: npm start
            displayName: Run if release task
# container:
# pool:
#   vmImage: ubuntu-latest

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'
