# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: CI_Frontend
  displayName: 'CI for Frontend'
  jobs:
  - job: __CI__
    displayName: 'CI JOB for Frontend'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: npm install
        displayName: install node dependencies
      - script: npm run build
        displayName: RUN BUILD

# - stage: CD-Frontend
#   displayName: 'CD for Frontend'
#   jobs:
#   - job: --CD--
#   - job: B2

# container:
# pool:
#   vmImage: ubuntu-latest

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'
